// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://btbptjbqctxwdygkyjsi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0YnB0amJxY3R4d2R5Z2t5anNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1ODAwOTYsImV4cCI6MjA2NTE1NjA5Nn0.CcsXkEzy2oRLFGibQ0G_elZpOJhxYpy7aloPgVPp1Yo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);